//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _ExcellOn_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banking
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<double> Money { get; set; }
        public Nullable<int> Deleted { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> CustomerId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Order Order { get; set; }
    }
}
